version: '3'
services:
  sqlite-container:
    image: alpine:latest  
    volumes:
      - ./sqlite-data:/data 
    command: sh -c "apk add --no-cache sqlite && sqlite3 /data/cambio.sqlite" 
    ports:
      - "54321:54321"